Revert "handling of luaposix for dynamic environments"
This reverts commit a71c2ebb8f813f0f650cf605eb5d488819f4aa29.

sorry, it breaks the build (the trivial #endif -> #else and
additional "error: 'report' was not declared in this scope)"


Origin commit data
------------------
Commit: https://github.com/Duckbox-Developers/neutrino-ddt/commit/8c88dfdc204577cbbc4ecb7af07882c0ff373245
Author: Stefan Seyfried <seife@tuxbox-git.slipkontur.de>
Date: 2013-04-27 (Sat, 27 Apr 2013)



------------------
This commit was generated by Migit