Revert "handling of luaposix for dynamic environments"
This reverts commit 51bc3c89f188991e0f9db6be50d4fc1c18d2a9f9.

sorry, it breaks the build (the trivial #endif -> #else and
additional "error: 'report' was not declared in this scope)"


Origin commit data
------------------
Branch: master
Commit: https://github.com/Duckbox-Developers/neutrino-ddt/commit/8c88dfdc204577cbbc4ecb7af07882c0ff373245
Author: Stefan Seyfried <seife@tuxbox-git.slipkontur.de>
Date: 2013-04-27 (Sat, 27 Apr 2013)



------------------
This commit was generated by Migit