Revert "- movieplayer: allow screenshots from stream"
- sh4 build not ok

"/build_source/neutrino-mp-ddt/src/gui/movieplayer.cpp:3524:9: error: 'put_time' is not a member of 'std'
ss << std::put_time(&tm, "%Y%m%d_%H%M%S");"

This reverts commit c64ff6aeb26cab17d1e6fa6b3ad9b47b9cd269bb.


Origin commit data
------------------
Commit: https://github.com/Duckbox-Developers/neutrino-ddt/commit/621b85c963ef28beb27c3660722879a57ea5afb2
Author: Frankenstone <dampf_acc@online.de>
Date: 2019-03-18 (Mon, 18 Mar 2019)



------------------
This commit was generated by Migit